# Generated by Django 4.2 on 2026-05-03 10:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdrianeProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('hobbies', wagtail.fields.RichTextField(blank=True)),
                ('favorite_games', wagtail.fields.RichTextField(blank=True)),
                ('favorite_food', wagtail.fields.RichTextField(blank=True)),
                ('favorite_music', wagtail.fields.RichTextField(blank=True)),
                ('favorite_artists', wagtail.fields.RichTextField(blank=True)),
                ('favorite_shows', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Profile Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
