# Generated by Django 4.2 on 2026-05-03 12:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_edrianeprofilepage_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='favorite_food',
        ),
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='favorite_games',
        ),
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='favorite_music',
        ),
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='favorite_shows',
        ),
        migrations.RemoveField(
            model_name='edrianeprofilepage',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='profile_sections',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.CharBlock(help_text='Anchor id like hobbies, games, food', max_length=100, required=True)), ('section_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('section_description', wagtail.blocks.TextBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='quick_links',
            field=wagtail.fields.StreamField([('quick_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
