# Generated by Django 4.2 on 2026-05-03 12:49

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_edrianeprofilepage_favorite_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='about_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hobbies_cards',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hobbies_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hobbies_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
