# Generated by Django 4.2 on 2026-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_edrianeprofilepage_about_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hero_cta_anchor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hero_micro_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
