# Generated by Django 4.2 on 2026-05-03 13:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_edrianeprofilepage_hero_cta_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrianeprofilepage',
            name='hero_polaroids',
            field=wagtail.fields.StreamField([('polaroid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
