# Generated by Django 4.2.21 on 2026-05-04 04:07

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_edrianeprofilepage_hero_polaroids'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_label',
            field=models.CharField(blank=True, default='Contact Us', help_text='Contact button label (leave blank to hide)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_url',
            field=models.CharField(blank=True, help_text='Contact button URL or mailto:', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='creators',
            field=wagtail.fields.StreamField([('creator', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('bio', wagtail.blocks.TextBlock(required=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock(required=False)), ('profile_page', wagtail.blocks.PageChooserBlock(help_text="Link to this person's profile page", required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='creators_heading',
            field=models.CharField(blank=True, default='Meet the Creators', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='creators_subheading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_anchor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_micro_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_polaroids',
            field=wagtail.fields.StreamField([('polaroid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nav_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(help_text='Link text shown in nav bar', max_length=100)), ('anchor', wagtail.blocks.CharBlock(help_text="Anchor id without #, e.g. 'hobbies'", max_length=100))]))], blank=True, help_text='Nav links between Home and Contact', use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quick_links',
            field=wagtail.fields.StreamField([('quick_link', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Small icon image (shown above title)', required=False)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('link_label', wagtail.blocks.CharBlock(help_text="CTA text, e.g. 'View Hobbies'", max_length=100, required=False)), ('link_anchor', wagtail.blocks.CharBlock(help_text="Anchor id without #, e.g. 'hobbies'", max_length=100, required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_title',
            field=models.CharField(blank=True, default='Our Favorites ✨', help_text='Logo text shown top-left', max_length=255),
        ),
    ]
