# Generated by Django 4.2.21 on 2026-05-05 06:25

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_contact_label_homepage_contact_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nav_links',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_label',
            field=models.CharField(blank=True, help_text="Optional 'About Us' nav link label (links to #about)", max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=models.CharField(blank=True, help_text="Contact Us button label in the navbar, e.g. 'Contact Us'", max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_url',
            field=models.CharField(blank=True, help_text='URL or mailto: for the contact button', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='creators',
            field=wagtail.fields.StreamField([('creator', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('bio', wagtail.blocks.TextBlock(help_text='Short one-liner shown on the card', required=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock(required=False)), ('profile_page', wagtail.blocks.PageChooserBlock(help_text="Links the 'View Archive' button to this person's profile page", required=False))]))], blank=True, help_text='One card per creator — avatar, name, bio, and link to their profile', use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='creators_heading',
            field=models.CharField(blank=True, default='Meet the Creators', help_text='Section heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='creators_subheading',
            field=models.CharField(blank=True, help_text='Optional subtitle below the heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(blank=True, help_text="Footer line, e.g. '© 2025 Artist Archive. All rights reserved. ♡'", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_anchor',
            field=models.CharField(blank=True, help_text="Section id the CTA scrolls to, e.g. 'creators'", max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, help_text="CTA button label, e.g. 'Explore Our Favorites'", max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Short paragraph below the heading'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text="Main hero heading, e.g. 'Our Favorites'", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_micro_title',
            field=models.CharField(blank=True, help_text='Small uppercase eyebrow label above the main heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_polaroids',
            field=wagtail.fields.StreamField([('polaroid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, help_text='Up to 3 polaroid-style photo cards stacked on the right side of the hero', use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text="Italic green continuation of the heading, e.g. 'Our World.'", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='quick_links',
            field=wagtail.fields.StreamField([('quick_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('icon_emoji', wagtail.blocks.CharBlock(help_text='Single emoji for the card icon, e.g. 🎮 🍜 🎵', max_length=8, required=False)), ('link_label', wagtail.blocks.CharBlock(help_text="CTA text, e.g. 'View Games'", max_length=100, required=False)), ('link_anchor', wagtail.blocks.CharBlock(help_text="Anchor id without #, e.g. 'games'", max_length=100, required=False))]))], blank=True, help_text='Horizontal strip of feature cards below the hero — one per section', use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_title',
            field=models.CharField(blank=True, default='Artist Archive ✨', help_text='Logo text shown top-left in the navbar', max_length=255),
        ),
    ]
